### ISSUE TITLE
Support for "multi lingual" versions of office

### ISSUE THREAD

**Issue by schlaubstar** [deadlydog/NotifyWhenMicrosoftOutlookReminderWindowIsOpen#1]
Hi,

I really like the approach and can help myself with the sourcecode but I would recommend that you make the text of the Window is configurable because the german versions title has the caption "1 Erinnerung(en)" instead of "1 Reminder(s)" and thus, your tool is not working.

**Comment by deadlydog** [comment]
Hey @schlaubstar v1.1.0 now has Advanced settings that allows you to specify the window title text to match against, so you should be able to adjust that for non-English Windows. I believe that should get you going :)
