### ISSUE TITLE
Improvement proposals

### ISSUE THREAD

**Issue by schlaubstar** [deadlydog/NotifyWhenMicrosoftOutlookReminderWindowIsOpen#2]
Although those are no a real issues but proposals for improvement: 

- I would heavily appreciate a link to this GitHub repository accessible from the settings dialog

- you could eliminate 'false positives by determining if the parent process of the found "Reminder(s)" window is Outlook

However: great approach and thanks for your efforts!

**Comment by deadlydog** [comment]
Both of these enhancements have been added to v1.1.0. Enjoy! :)
